# Path to the playlist file to load.
# Optional - If not specified, it must be specified via CLI parameter.
playlist = "/path/to/playlist.toml"

# Path to a directory used to store program data.
# This is used to store the running state of the program,
# so it can be resumed on startup
# Required
data_dir = "~/.paper-frame/"

# ePaper Display Driver
# Be sure you have the correct driver library installed.
# If this driver is not found, a dummy EPD will be used that logs to the console
# Required
epd = "waveshare_epd.epd7in5_V2"

# Logging Level
# DEBUG, INFO, WARN, ERROR, FATAL
# Required
log_level = "INFO"
